"""entity image gallery

Revision ID: 15abe83248a0
Revises: a1b2c3d4e5f6
Create Date: 2026-08-06 21:35:25.828298
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '15abe83248a0'
down_revision: str | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_images',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_images_entity_id'), 'entity_images', ['entity_id'], unique=False)
    # Covers uploaded before the gallery existed become its first row
    op.execute(
        """
        INSERT INTO entity_images (id, entity_id, url, caption, position, created_at, updated_at)
        SELECT gen_random_uuid(), e.id, e.image_url, NULL, 0, now(), now()
        FROM entities e
        WHERE e.image_url IS NOT NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_images_entity_id'), table_name='entity_images')
    op.drop_table('entity_images')
    # ### end Alembic commands ###
