"""add workspace settings

Revision ID: 4f4b0f585dcc
Revises: 79b9560a0f64
Create Date: 2026-08-06 09:01:53.771940
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '4f4b0f585dcc'
down_revision: str | None = '79b9560a0f64'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace')
    # ### end Alembic commands ###
