"""campaigns, entities, links, cast

Revision ID: be2995e09215
Revises: 4f4b0f585dcc
Create Date: 2026-08-06 19:35:38.156103
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'be2995e09215'
down_revision: str | None = '4f4b0f585dcc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('display_token', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_display_token'), 'campaigns', ['display_token'], unique=True)
    op.create_index(op.f('ix_campaigns_owner_id'), 'campaigns', ['owner_id'], unique=False)
    op.create_index(op.f('ix_campaigns_slug'), 'campaigns', ['slug'], unique=True)
    op.create_table('campaign_members',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('player', 'dm', name='campaign_role'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id', name='uq_member_per_campaign')
    )
    op.create_index(op.f('ix_campaign_members_campaign_id'), 'campaign_members', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_members_user_id'), 'campaign_members', ['user_id'], unique=False)
    op.create_table('cast_states',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('idle', 'image', 'text', 'initiative', 'map', name='cast_mode'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cast_states_campaign_id'), 'cast_states', ['campaign_id'], unique=True)
    op.create_table('entities',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('npc', 'location', 'item', 'faction', 'note', name='entity_type'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('visibility', sa.Enum('dm_only', 'shared', 'public', name='entity_visibility'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('simple', coalesce(name, '')), 'A') || setweight(to_tsvector('simple', coalesce(summary, '')), 'B') || setweight(to_tsvector('simple', coalesce(body, '')), 'C')", persisted=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'slug', name='uq_entity_slug_per_campaign')
    )
    op.create_index(op.f('ix_entities_campaign_id'), 'entities', ['campaign_id'], unique=False)
    op.create_index('ix_entities_campaign_type', 'entities', ['campaign_id', 'type'], unique=False)
    op.create_index('ix_entities_search', 'entities', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('entity_links',
    sa.Column('from_id', sa.Uuid(), nullable=False),
    sa.Column('to_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.Enum('mentions', 'member_of', 'located_in', 'owns', 'related_to', name='link_relation'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', 'relation', name='uq_entity_link')
    )
    op.create_index(op.f('ix_entity_links_from_id'), 'entity_links', ['from_id'], unique=False)
    op.create_index('ix_entity_links_to', 'entity_links', ['to_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entity_links_to', table_name='entity_links')
    op.drop_index(op.f('ix_entity_links_from_id'), table_name='entity_links')
    op.drop_table('entity_links')
    op.drop_index('ix_entities_search', table_name='entities', postgresql_using='gin')
    op.drop_index('ix_entities_campaign_type', table_name='entities')
    op.drop_index(op.f('ix_entities_campaign_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_cast_states_campaign_id'), table_name='cast_states')
    op.drop_table('cast_states')
    op.drop_index(op.f('ix_campaign_members_user_id'), table_name='campaign_members')
    op.drop_index(op.f('ix_campaign_members_campaign_id'), table_name='campaign_members')
    op.drop_table('campaign_members')
    op.drop_index(op.f('ix_campaigns_slug'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_owner_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_display_token'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
